"""
Databricks App:
- Serves a small Flask API + UI for support tickets
- Reads/writes to Lakebase (Databricks-managed Postgres) via lakebase.py

Run locally:
    python app.py
Deploy as a Databricks App using app.yaml.
"""

import logging
import os

from databricks.sdk import WorkspaceClient
from flask import Flask, jsonify, render_template, request

import lakebase

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("tickets-app")

app = Flask(__name__)
_w = WorkspaceClient()

TICKETS_TABLE = os.environ.get("TICKETS_TABLE_NAME", "tickets")
MESSAGES_TABLE = os.environ.get("TICKET_MESSAGES_TABLE_NAME", "ticket_messages")

VALID_STATUSES = ("open", "in_progress", "solved")
VALID_PRIORITIES = ("low", "medium", "high", "urgent")
VALID_CATEGORIES = ("general", "billing", "technical", "account", "other")

TITLE_MIN_LEN = 3
TITLE_MAX_LEN = 200
MESSAGE_MIN_LEN = 1
MESSAGE_MAX_LEN = 5000

TICKET_COLUMNS = (
    "ticket_id, title, status, priority, category, created_by, created_at"
)


def ensure_tables():
    """Create tickets and ticket_messages tables in Lakebase if they don't exist yet.

    IDs are BIGINT to match existing Lakebase tables. ticket_messages.ticket_id is
    not declared as a DB foreign key because the existing tickets table may not
    have a PRIMARY KEY/UNIQUE on ticket_id (Postgres requires that for FKs).
    The API still enforces that messages reference a real ticket.
    """
    lakebase.run_write(
        f"""
        CREATE TABLE IF NOT EXISTS {TICKETS_TABLE} (
            ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open',
            priority TEXT NOT NULL DEFAULT 'medium',
            category TEXT NOT NULL DEFAULT 'general',
            created_by TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    # Migrate existing tickets tables that predate priority/category.
    for column, default in (("priority", "medium"), ("category", "general")):
        try:
            lakebase.run_write(
                f"""
                ALTER TABLE {TICKETS_TABLE}
                ADD COLUMN IF NOT EXISTS {column} TEXT NOT NULL DEFAULT '{default}'
                """
            )
        except Exception:
            logger.warning(
                "Could not add column %s on %s", column, TICKETS_TABLE, exc_info=True
            )

    try:
        lakebase.run_write(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    JOIN unnest(c.conkey) AS col(attnum) ON true
                    JOIN pg_attribute a
                      ON a.attrelid = t.oid AND a.attnum = col.attnum
                    WHERE t.relname = '{TICKETS_TABLE}'
                      AND c.contype IN ('p', 'u')
                      AND a.attname = 'ticket_id'
                ) THEN
                    ALTER TABLE {TICKETS_TABLE}
                        ADD CONSTRAINT tickets_ticket_id_key UNIQUE (ticket_id);
                END IF;
            END $$;
            """
        )
    except Exception:
        logger.warning(
            "Could not ensure UNIQUE(ticket_id) on %s; continuing without DB FK",
            TICKETS_TABLE,
            exc_info=True,
        )

    try:
        lakebase.run_write(
            f"""
            CREATE TABLE IF NOT EXISTS {MESSAGES_TABLE} (
                message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticket_id BIGINT NOT NULL REFERENCES {TICKETS_TABLE}(ticket_id),
                message_text TEXT NOT NULL,
                author TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
    except Exception:
        logger.warning(
            "Creating %s without foreign key (tickets.ticket_id is not unique)",
            MESSAGES_TABLE,
            exc_info=True,
        )
        lakebase.run_write(
            f"""
            CREATE TABLE IF NOT EXISTS {MESSAGES_TABLE} (
                message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticket_id BIGINT NOT NULL,
                message_text TEXT NOT NULL,
                author TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )

    lakebase.run_write(
        f"""
        CREATE INDEX IF NOT EXISTS {MESSAGES_TABLE}_ticket_id_idx
        ON {MESSAGES_TABLE} (ticket_id)
        """
    )


def _parse_ticket_id(ticket_id: str) -> int | None:
    try:
        return int(ticket_id)
    except (TypeError, ValueError):
        return None


def _current_user_email() -> str:
    """
    Resolve the current user's email.

    Databricks Apps inject the logged-in user's identity via the
    X-Forwarded-Email header on every request. Fall back to the Databricks
    SDK's current_user API for local development where that header isn't set.
    """
    header_email = request.headers.get("X-Forwarded-Email")
    if header_email:
        return header_email
    return _w.current_user.me().user_name


def _serialize_row(row: dict) -> dict:
    """Convert DB row values (e.g. datetime) into JSON-safe types."""
    out = dict(row)
    for key, value in out.items():
        if hasattr(value, "isoformat"):
            out[key] = value.isoformat()
    return out


def _error(message: str, status: int = 400, *, fields: dict | None = None):
    payload = {"error": message}
    if fields:
        payload["fields"] = fields
    return jsonify(payload), status


def _validate_title(title: object) -> tuple[str | None, str | None]:
    if not isinstance(title, str):
        return None, "Title is required and must be text."
    cleaned = title.strip()
    if not cleaned:
        return None, "Title is required."
    if len(cleaned) < TITLE_MIN_LEN:
        return None, f"Title must be at least {TITLE_MIN_LEN} characters."
    if len(cleaned) > TITLE_MAX_LEN:
        return None, f"Title must be at most {TITLE_MAX_LEN} characters."
    return cleaned, None


def _validate_choice(
    value: object,
    *,
    field: str,
    allowed: tuple[str, ...],
    default: str | None = None,
    required: bool = False,
) -> tuple[str | None, str | None]:
    if value is None or (isinstance(value, str) and not value.strip()):
        if required:
            return None, f"{field} is required. Choose one of: {', '.join(allowed)}."
        return default, None
    if not isinstance(value, str):
        return None, f"{field} must be text. Allowed values: {', '.join(allowed)}."
    cleaned = value.strip().lower()
    if cleaned not in allowed:
        return None, f"Invalid {field} '{value}'. Allowed values: {', '.join(allowed)}."
    return cleaned, None


def _validate_message_text(message_text: object) -> tuple[str | None, str | None]:
    if not isinstance(message_text, str):
        return None, "Message text is required and must be text."
    cleaned = message_text.strip()
    if len(cleaned) < MESSAGE_MIN_LEN:
        return None, "Message text is required."
    if len(cleaned) > MESSAGE_MAX_LEN:
        return None, f"Message text must be at most {MESSAGE_MAX_LEN} characters."
    return cleaned, None


def _get_ticket_or_none(ticket_id: int) -> dict | None:
    rows = lakebase.run_query(
        f"""
        SELECT {TICKET_COLUMNS}
        FROM {TICKETS_TABLE}
        WHERE ticket_id = %s
        """,
        (ticket_id,),
    )
    return rows[0] if rows else None


@app.route("/healthz")
def healthz():
    return jsonify({"status": "ok"})


@app.errorhandler(Exception)
def handle_exception(err):
    """Ensure all unhandled errors return JSON (not an HTML error page)."""
    logger.exception("Unhandled exception while processing request")
    status_code = getattr(err, "code", 500)
    if not isinstance(status_code, int):
        status_code = 500
    return jsonify({"error": str(err)}), status_code


@app.route("/")
def index():
    """Support tickets UI."""
    return render_template("index.html")


@app.route("/meta")
def meta():
    """Return allowed enum values for the UI."""
    return jsonify(
        {
            "statuses": list(VALID_STATUSES),
            "priorities": list(VALID_PRIORITIES),
            "categories": list(VALID_CATEGORIES),
            "limits": {
                "title_min": TITLE_MIN_LEN,
                "title_max": TITLE_MAX_LEN,
                "message_min": MESSAGE_MIN_LEN,
                "message_max": MESSAGE_MAX_LEN,
            },
        }
    )


@app.route("/tickets/stats")
def ticket_stats():
    """Return aggregate ticket counts by status, priority, and category."""
    ensure_tables()
    total_rows = lakebase.run_query(f"SELECT COUNT(*) AS total FROM {TICKETS_TABLE}")
    total = int(total_rows[0]["total"]) if total_rows else 0

    def _counts(column: str, allowed: tuple[str, ...]) -> dict[str, int]:
        rows = lakebase.run_query(
            f"""
            SELECT {column} AS key, COUNT(*) AS count
            FROM {TICKETS_TABLE}
            GROUP BY {column}
            """
        )
        counts = {name: 0 for name in allowed}
        for row in rows:
            key = row.get("key")
            if key in counts:
                counts[key] = int(row["count"])
            elif key is not None:
                counts[str(key)] = int(row["count"])
        return counts

    return jsonify(
        {
            "total": total,
            "by_status": _counts("status", VALID_STATUSES),
            "by_priority": _counts("priority", VALID_PRIORITIES),
            "by_category": _counts("category", VALID_CATEGORIES),
        }
    )


@app.route("/tickets", methods=["GET"])
def list_tickets():
    """Return support tickets, optionally filtered by status, newest first."""
    ensure_tables()

    status = request.args.get("status")
    priority = request.args.get("priority")
    category = request.args.get("category")
    fields: dict[str, str] = {}

    if status not in (None, "", "all"):
        cleaned, err = _validate_choice(
            status, field="status", allowed=VALID_STATUSES, required=True
        )
        if err:
            fields["status"] = err
        status = cleaned
    else:
        status = None

    if priority not in (None, "", "all"):
        cleaned, err = _validate_choice(
            priority, field="priority", allowed=VALID_PRIORITIES, required=True
        )
        if err:
            fields["priority"] = err
        priority = cleaned
    else:
        priority = None

    if category not in (None, "", "all"):
        cleaned, err = _validate_choice(
            category, field="category", allowed=VALID_CATEGORIES, required=True
        )
        if err:
            fields["category"] = err
        category = cleaned
    else:
        category = None

    if fields:
        return _error("Invalid filter parameters.", fields=fields)

    clauses = []
    params: list = []
    if status:
        clauses.append("status = %s")
        params.append(status)
    if priority:
        clauses.append("priority = %s")
        params.append(priority)
    if category:
        clauses.append("category = %s")
        params.append(category)

    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    rows = lakebase.run_query(
        f"""
        SELECT {TICKET_COLUMNS}
        FROM {TICKETS_TABLE}
        {where}
        ORDER BY created_at DESC
        """,
        tuple(params) if params else None,
    )
    return jsonify([_serialize_row(r) for r in rows])


@app.route("/tickets", methods=["POST"])
def create_ticket():
    """Create a new support ticket."""
    ensure_tables()

    data = request.get_json(silent=True)
    if data is None:
        return _error("Request body must be JSON with ticket fields.")

    fields: dict[str, str] = {}
    title, err = _validate_title(data.get("title"))
    if err:
        fields["title"] = err

    status, err = _validate_choice(
        data.get("status"),
        field="status",
        allowed=VALID_STATUSES,
        default="open",
    )
    if err:
        fields["status"] = err

    priority, err = _validate_choice(
        data.get("priority"),
        field="priority",
        allowed=VALID_PRIORITIES,
        default="medium",
    )
    if err:
        fields["priority"] = err

    category, err = _validate_choice(
        data.get("category"),
        field="category",
        allowed=VALID_CATEGORIES,
        default="general",
    )
    if err:
        fields["category"] = err

    if fields:
        return _error("Please fix the highlighted fields and try again.", fields=fields)

    created_by = _current_user_email()
    rows = lakebase.run_write_returning(
        f"""
        INSERT INTO {TICKETS_TABLE}
            (title, status, priority, category, created_by, created_at)
        VALUES (%s, %s, %s, %s, %s, now())
        RETURNING {TICKET_COLUMNS}
        """,
        (title, status, priority, category, created_by),
    )
    return jsonify(_serialize_row(rows[0])), 201


@app.route("/tickets/<ticket_id>", methods=["GET"])
def get_ticket(ticket_id: str):
    """Return a single ticket by id."""
    ensure_tables()
    parsed_id = _parse_ticket_id(ticket_id)
    if parsed_id is None:
        return _error(
            "Invalid ticket id. Use a numeric ticket_id from the tickets list."
        )

    ticket = _get_ticket_or_none(parsed_id)
    if not ticket:
        return _error(f"Ticket #{parsed_id} was not found.", 404)
    return jsonify(_serialize_row(ticket))


@app.route("/tickets/<ticket_id>", methods=["DELETE"])
def delete_ticket(ticket_id: str):
    """Delete a ticket and all of its messages."""
    ensure_tables()
    parsed_id = _parse_ticket_id(ticket_id)
    if parsed_id is None:
        return _error(
            "Invalid ticket id. Use a numeric ticket_id from the tickets list."
        )

    ticket = _get_ticket_or_none(parsed_id)
    if not ticket:
        return _error(f"Ticket #{parsed_id} was not found.", 404)

    lakebase.run_write(
        f"DELETE FROM {MESSAGES_TABLE} WHERE ticket_id = %s",
        (parsed_id,),
    )
    deleted = lakebase.run_write(
        f"DELETE FROM {TICKETS_TABLE} WHERE ticket_id = %s",
        (parsed_id,),
    )
    if deleted == 0:
        return _error(f"Ticket #{parsed_id} was not found.", 404)

    return jsonify(
        {
            "deleted": True,
            "ticket_id": parsed_id,
            "title": ticket.get("title"),
        }
    )


@app.route("/tickets/<ticket_id>/status", methods=["PATCH", "PUT"])
def update_ticket_status(ticket_id: str):
    """Update a ticket's status."""
    ensure_tables()
    parsed_id = _parse_ticket_id(ticket_id)
    if parsed_id is None:
        return _error(
            "Invalid ticket id. Use a numeric ticket_id from the tickets list."
        )

    data = request.get_json(silent=True)
    if data is None:
        return _error('Request body must be JSON, e.g. {"status": "solved"}.')

    status, err = _validate_choice(
        data.get("status"),
        field="status",
        allowed=VALID_STATUSES,
        required=True,
    )
    if err:
        return _error(err, fields={"status": err})

    updated = lakebase.run_write(
        f"""
        UPDATE {TICKETS_TABLE}
        SET status = %s
        WHERE ticket_id = %s
        """,
        (status, parsed_id),
    )
    if updated == 0:
        return _error(f"Ticket #{parsed_id} was not found.", 404)

    ticket = _get_ticket_or_none(parsed_id)
    return jsonify(_serialize_row(ticket))


@app.route("/tickets/<ticket_id>", methods=["PATCH"])
def update_ticket(ticket_id: str):
    """Update ticket fields (status, priority, and/or category)."""
    ensure_tables()
    parsed_id = _parse_ticket_id(ticket_id)
    if parsed_id is None:
        return _error(
            "Invalid ticket id. Use a numeric ticket_id from the tickets list."
        )

    data = request.get_json(silent=True)
    if data is None:
        return _error("Request body must be JSON with fields to update.")

    if not _get_ticket_or_none(parsed_id):
        return _error(f"Ticket #{parsed_id} was not found.", 404)

    fields: dict[str, str] = {}
    updates: list[str] = []
    params: list = []

    if "status" in data:
        status, err = _validate_choice(
            data.get("status"),
            field="status",
            allowed=VALID_STATUSES,
            required=True,
        )
        if err:
            fields["status"] = err
        else:
            updates.append("status = %s")
            params.append(status)

    if "priority" in data:
        priority, err = _validate_choice(
            data.get("priority"),
            field="priority",
            allowed=VALID_PRIORITIES,
            required=True,
        )
        if err:
            fields["priority"] = err
        else:
            updates.append("priority = %s")
            params.append(priority)

    if "category" in data:
        category, err = _validate_choice(
            data.get("category"),
            field="category",
            allowed=VALID_CATEGORIES,
            required=True,
        )
        if err:
            fields["category"] = err
        else:
            updates.append("category = %s")
            params.append(category)

    if fields:
        return _error("Please fix the highlighted fields and try again.", fields=fields)
    if not updates:
        return _error(
            "No updatable fields provided. Send status, priority, and/or category."
        )

    params.append(parsed_id)
    lakebase.run_write(
        f"""
        UPDATE {TICKETS_TABLE}
        SET {', '.join(updates)}
        WHERE ticket_id = %s
        """,
        tuple(params),
    )
    ticket = _get_ticket_or_none(parsed_id)
    return jsonify(_serialize_row(ticket))


@app.route("/tickets/<ticket_id>/messages", methods=["GET"])
def list_messages(ticket_id: str):
    """Return all messages for a ticket, oldest first."""
    ensure_tables()
    parsed_id = _parse_ticket_id(ticket_id)
    if parsed_id is None:
        return _error(
            "Invalid ticket id. Use a numeric ticket_id from the tickets list."
        )

    if not _get_ticket_or_none(parsed_id):
        return _error(f"Ticket #{parsed_id} was not found.", 404)

    rows = lakebase.run_query(
        f"""
        SELECT message_id, ticket_id, message_text, author, created_at
        FROM {MESSAGES_TABLE}
        WHERE ticket_id = %s
        ORDER BY created_at ASC
        """,
        (parsed_id,),
    )
    return jsonify([_serialize_row(r) for r in rows])


@app.route("/tickets/<ticket_id>/messages", methods=["POST"])
def add_message(ticket_id: str):
    """Add a message to an existing ticket."""
    ensure_tables()
    parsed_id = _parse_ticket_id(ticket_id)
    if parsed_id is None:
        return _error(
            "Invalid ticket id. Use a numeric ticket_id from the tickets list."
        )

    if not _get_ticket_or_none(parsed_id):
        return _error(f"Ticket #{parsed_id} was not found.", 404)

    data = request.get_json(silent=True)
    if data is None:
        return _error('Request body must be JSON, e.g. {"message_text": "Hello"}.')

    message_text, err = _validate_message_text(data.get("message_text"))
    if err:
        return _error(err, fields={"message_text": err})

    author = _current_user_email()
    rows = lakebase.run_write_returning(
        f"""
        INSERT INTO {MESSAGES_TABLE} (ticket_id, message_text, author, created_at)
        VALUES (%s, %s, %s, now())
        RETURNING message_id, ticket_id, message_text, author, created_at
        """,
        (parsed_id, message_text, author),
    )
    return jsonify(_serialize_row(rows[0])), 201


if __name__ == "__main__":
    host = os.getenv("FLASK_RUN_HOST", "0.0.0.0")
    port = int(os.getenv("FLASK_RUN_PORT", 8000))
    app.run(debug=True, host=host, port=port)
    print(f"Flask app running on http://{host}:{port}")
